### ISSUE TITLE
`cohen_f` output in `ANOVA_exact()` for 2x2 interaction

### ISSUE THREAD

**Issue by crsh** [arcaldwell49/Superpower#9]
Hi there,

I've been playing with this super useful package, trying to do a power analysis. I've started out reproducing power analysis I've done in G*Power and I'm having some trouble understanding the output of `ANOVA_exact()`. I'm wondering whether the following is intended behavior and I'm just missing something.

The following is my G*Power sensitivity analysis for the interaction in a 2x2 within-between design.

~~~
F tests - ANOVA: Repeated measures, within-between interaction
Analysis:	Sensitivity: Compute required effect size 
Input:	α err prob	                      =	0.05
	Power (1-β err prob)	              =	0.95
	Total sample size	              =	150
	Number of groups                      =	2
	Number of measurements                =	2
	Corr among rep measures	              =	0.5
	Nonsphericity correction ε            =	1
Output:	Noncentrality parameter λ	      =	13.1657351
	Critical F	                      =	3.9050601
      	Numerator df	                      =	1.0000000
      	Denominator df	                      =	148
      	Effect size f	                      =	0.1481313
~~~

I then tried to reproduce the results in a power analysis.

~~~r
f <- 0.1481313
mu <- c(-f, f, f,-f)
n <- 75
sd <- 1
r <- 0.5
design <- "2w*2b"
alpha_level <- 0.05

design_result <- ANOVA_design(
  design = design,
  n = n,
  mu = mu,
  sd = sd,
  r = r,
)

exact_result <- ANOVA_exact(design_result,
                            alpha_level = alpha_level,
                            verbose = FALSE)

exact_result$main_results
~~~
~~~
       power partial_eta_squared      cohen_f non_centrality
b    5.00000        6.506520e-33 8.066300e-17   9.629650e-31
a    5.00000        9.344536e-33 9.666714e-17   1.382991e-30
b:a 94.99999        8.169063e-02 2.982577e-01   1.316573e+01
~~~

While the computed power and the noncentrality parameter match the results form G*Power, `cohen_f` seems to be exactly `2*f` (i.e. Cohen's d rather than f), which has me scratching my head. Shouldn't I be getting the f I put in?

**Comment by Lakens** [comment]
Hi,
the confusion is due to the fact how G*power computes effect sizes for within designs, and how it takes into account the effect size. We explain this here: https://aaroncaldwell.us/SuperpowerBook/repeated-measures-anova.html. 
The confusion might in part be our fault - we say we give back Cohen's f, but whenever it is a within factor or interaction, we return Cohen's f(U). See the attached screenshot that reproduces the Superpower output. 
![image](https://user-images.githubusercontent.com/6490081/73440163-157ac200-4351-11ea-987e-9e6e36b28220.png)
You get this output by going into the 'Options' menu, and selecting 'As in SPSS' (which is really a 'As everybody else does it'). 
Again, the fault is our for not labeling the output. We might need to add a note - you will not be the last to mention this! 
Because you are correct, also in your example, that the Cohen's f is the value you typed in (calculated as):
# Cohen, 1988, formula 8.2.1 and 8.2.2
f <- sqrt(sum((mu - mean(mu)) ^ 2) / length(mu)) / sd
The confusion between f and f(U) is worth clearing up. Thanks for pointing it out. We will see how we prevent this confusion in the package.
